# General Config
title = "rsapi"
description = "Rust Web App"

# Web Framework
[[deps.cargo]]
name = "axum"
features = ["macros"]

[[deps.cargo]]
name = "tokio" 
features = ["macros", "rt-multi-thread"] 

[[deps.cargo]]
name = "tower"

[[deps.cargo]]
name = "tower-http"
features = ["cors"]

[[deps.cargo]]
name = "serde"

[[deps.cargo]]
name = "serde-json"

[[deps.cargo]]
name = "axum_test"

[[deps.cargo]]
name = "time"
features = ["macros", "serde"]

[[deps.cargo]]
name = "validator"
features = ["derive"]

[[deps.cargo]]
name = "strum"

[[deps.cargo]]
name = "strum_macros"
