# General Config
title = "rsapi"
description = "Rust Web App"

# Web Framework
[[deps.cargo]]
name = "axum"

[[deps.cargo]]
name = "tokio" 
features = ["macros", "rt-multi-thread"] 

[[deps.cargo]]
name = "tower"

[[deps.cargo]]
name = "tower-http"
features = ["cors"]

[[deps.cargo]]
name = "serde"
